import type { EnumTable } from '../core/model';

export const enumTables: EnumTable[] = [
  {
    id: 'ethertype',
    name: 'EtherTypes',
    values: {
      0x0800: 'IPv4',
      0x0806: 'ARP',
      0x8100: '802.1Q VLAN',
      0x86dd: 'IPv6',
      0x8847: 'MPLS unicast',
      0x8848: 'MPLS multicast',
      0x8863: 'PPPoE Discovery',
      0x8864: 'PPPoE Session',
      0x88a8: '802.1ad Q-in-Q',
      0x88cc: 'LLDP',
    },
  },
  {
    id: 'ip-proto',
    name: 'IP protocol numbers',
    values: {
      1: 'ICMP',
      2: 'IGMP',
      4: 'IPv4 (encapsulated)',
      6: 'TCP',
      17: 'UDP',
      41: 'IPv6 (encapsulated)',
      47: 'GRE',
      50: 'ESP (IPsec)',
      51: 'AH (IPsec)',
      88: 'EIGRP',
      58: 'ICMPv6',
      89: 'OSPF',
      103: 'PIM',
      112: 'VRRP',
      115: 'L2TPv3',
      132: 'SCTP',
    },
  },
  {
    id: 'well-known-port',
    name: 'Well-known ports',
    values: {
      20: 'FTP data',
      21: 'FTP control',
      22: 'SSH',
      23: 'Telnet',
      25: 'SMTP',
      53: 'DNS',
      67: 'DHCP server',
      68: 'DHCP client',
      69: 'TFTP',
      80: 'HTTP',
      110: 'POP3',
      123: 'NTP',
      143: 'IMAP',
      179: 'BGP',
      443: 'HTTPS',
      137: 'NetBIOS name service',
      445: 'SMB',
      502: 'Modbus',
      514: 'Syslog',
      520: 'RIP',
      554: 'RTSP',
      546: 'DHCPv6 client',
      547: 'DHCPv6 server',
      1701: 'L2TP',
      1812: 'RADIUS auth',
      1883: 'MQTT',
      1985: 'HSRP',
      2055: 'NetFlow',
      2152: 'GTP-U',
      3478: 'STUN',
      3784: 'BFD control',
      4789: 'VXLAN',
      1900: 'SSDP',
      5004: 'RTP',
      5005: 'RTCP',
      5060: 'SIP',
      5353: 'mDNS',
      5355: 'LLMNR',
      5683: 'CoAP',
      6081: 'GENEVE',
      6667: 'IRC',
      51820: 'WireGuard',
    },
  },
  {
    id: 'icmp-type',
    name: 'ICMP types',
    values: {
      0: 'Echo reply',
      3: 'Destination unreachable',
      5: 'Redirect',
      8: 'Echo request',
      11: 'Time exceeded',
      13: 'Timestamp request',
      14: 'Timestamp reply',
    },
  },
  {
    id: 'icmpv6-type',
    name: 'ICMPv6 types',
    values: {
      1: 'Destination unreachable',
      2: 'Packet too big',
      3: 'Time exceeded',
      4: 'Parameter problem',
      128: 'Echo request',
      129: 'Echo reply',
      133: 'Router solicitation',
      134: 'Router advertisement',
      135: 'Neighbor solicitation',
      136: 'Neighbor advertisement',
    },
  },
  {
    id: 'arp-oper',
    name: 'ARP operations',
    values: { 1: 'Request', 2: 'Reply' },
  },
  {
    id: 'dns-type',
    name: 'DNS record types',
    values: { 1: 'A', 2: 'NS', 5: 'CNAME', 6: 'SOA', 12: 'PTR', 15: 'MX', 16: 'TXT', 28: 'AAAA', 33: 'SRV', 255: 'ANY' },
  },
  {
    id: 'dns-class',
    name: 'DNS classes',
    values: { 1: 'IN', 3: 'CH', 4: 'HS', 255: 'ANY' },
  },
  {
    id: 'dhcp-op',
    name: 'DHCP op codes',
    values: { 1: 'BOOTREQUEST', 2: 'BOOTREPLY' },
  },
  {
    id: 'tls-content',
    name: 'TLS content types',
    values: { 20: 'ChangeCipherSpec', 21: 'Alert', 22: 'Handshake', 23: 'ApplicationData' },
  },
  {
    id: 'tls-version',
    name: 'TLS versions',
    values: { 0x0301: 'TLS 1.0', 0x0302: 'TLS 1.1', 0x0303: 'TLS 1.2 (also used by 1.3 records)' },
  },
  {
    id: 'ntp-mode',
    name: 'NTP modes',
    values: { 1: 'Symmetric active', 2: 'Symmetric passive', 3: 'Client', 4: 'Server', 5: 'Broadcast' },
  },
  {
    id: 'ospf-type',
    name: 'OSPF packet types',
    values: { 1: 'Hello', 2: 'Database Description', 3: 'LS Request', 4: 'LS Update', 5: 'LS Ack' },
  },
  {
    id: 'bgp-type',
    name: 'BGP message types',
    values: { 1: 'OPEN', 2: 'UPDATE', 3: 'NOTIFICATION', 4: 'KEEPALIVE' },
  },
  {
    id: 'ppp-proto',
    name: 'PPP protocol numbers',
    values: { 0x0021: 'IPv4', 0x0057: 'IPv6', 0xc021: 'LCP', 0xc023: 'PAP', 0xc223: 'CHAP', 0x8021: 'IPCP' },
  },
  {
    id: 'pppoe-code',
    name: 'PPPoE codes',
    values: { 0x00: 'Session data', 0x09: 'PADI', 0x07: 'PADO', 0x19: 'PADR', 0x65: 'PADS', 0xa7: 'PADT' },
  },
  {
    id: 'igmp-type',
    name: 'IGMP message types',
    values: { 0x11: 'Membership query', 0x12: 'v1 membership report', 0x16: 'v2 membership report', 0x17: 'Leave group', 0x22: 'v3 membership report' },
  },
  {
    id: 'dscp',
    name: 'DSCP values',
    values: { 0: 'Default (CS0)', 8: 'CS1', 16: 'CS2', 24: 'CS3', 32: 'CS4', 40: 'CS5', 46: 'EF', 48: 'CS6', 56: 'CS7' },
  },
  {
    id: 'tftp-opcode',
    name: 'TFTP opcodes',
    values: { 1: 'RRQ (read)', 2: 'WRQ (write)', 3: 'DATA', 4: 'ACK', 5: 'ERROR' },
  },
  {
    id: 'radius-code',
    name: 'RADIUS codes',
    values: { 1: 'Access-Request', 2: 'Access-Accept', 3: 'Access-Reject', 4: 'Accounting-Request', 5: 'Accounting-Response', 11: 'Access-Challenge' },
  },
  {
    id: 'dhcpv6-msg-type',
    name: 'DHCPv6 message types',
    values: { 1: 'Solicit', 2: 'Advertise', 3: 'Request', 4: 'Confirm', 5: 'Renew', 6: 'Rebind', 7: 'Reply', 8: 'Release', 9: 'Decline' },
  },
  {
    id: 'eigrp-opcode',
    name: 'EIGRP opcodes',
    values: { 1: 'Update', 3: 'Query', 4: 'Reply', 5: 'Hello', 10: 'SIA-Query', 11: 'SIA-Reply' },
  },
  {
    id: 'hsrp-opcode',
    name: 'HSRP opcodes',
    values: { 0: 'Hello', 1: 'Coup', 2: 'Resign' },
  },
  {
    id: 'hsrp-state',
    name: 'HSRP states',
    values: { 0: 'Initial', 1: 'Learn', 2: 'Listen', 4: 'Speak', 8: 'Standby', 16: 'Active' },
  },
  {
    id: 'bfd-state',
    name: 'BFD session states',
    values: { 0: 'AdminDown', 1: 'Down', 2: 'Init', 3: 'Up' },
  },
  {
    id: 'stun-type',
    name: 'STUN message types',
    values: { 0x0001: 'Binding Request', 0x0101: 'Binding Success', 0x0111: 'Binding Error' },
  },
  {
    id: 'mqtt-type',
    name: 'MQTT packet types',
    values: { 1: 'CONNECT', 2: 'CONNACK', 3: 'PUBLISH', 8: 'SUBSCRIBE', 9: 'SUBACK', 12: 'PINGREQ', 13: 'PINGRESP', 14: 'DISCONNECT' },
  },
  {
    id: 'coap-code',
    name: 'CoAP codes',
    values: { 1: '0.01 GET', 2: '0.02 POST', 3: '0.03 PUT', 4: '0.04 DELETE', 69: '2.05 Content', 132: '4.04 Not Found' },
  },
  {
    id: 'http2-frame-type',
    name: 'HTTP/2 frame types',
    values: { 0: 'DATA', 1: 'HEADERS', 2: 'PRIORITY', 3: 'RST_STREAM', 4: 'SETTINGS', 6: 'PING', 7: 'GOAWAY', 8: 'WINDOW_UPDATE' },
  },
  {
    id: 'smb2-command',
    name: 'SMB2 commands',
    values: { 0: 'NEGOTIATE', 1: 'SESSION_SETUP', 3: 'TREE_CONNECT', 5: 'CREATE', 8: 'READ', 9: 'WRITE', 16: 'QUERY_INFO' },
  },
  {
    id: 'wireguard-type',
    name: 'WireGuard message types',
    values: { 1: 'Handshake Initiation', 2: 'Handshake Response', 3: 'Cookie Reply', 4: 'Transport Data' },
  },
  {
    id: 'rtcp-pt',
    name: 'RTCP packet types',
    values: { 200: 'Sender Report', 201: 'Receiver Report', 202: 'SDES', 203: 'BYE' },
  },
  {
    id: 'rtp-pt',
    name: 'RTP payload types',
    values: { 0: 'PCMU', 8: 'PCMA', 10: 'L16 stereo', 26: 'JPEG', 96: 'dynamic' },
  },
  {
    id: 'stp-bpdu-type',
    name: 'STP BPDU types',
    values: { 0: 'Configuration', 2: 'RSTP', 128: 'Topology Change Notification' },
  },
  {
    id: 'modbus-function',
    name: 'Modbus function codes',
    values: { 1: 'Read Coils', 3: 'Read Holding Registers', 5: 'Write Single Coil', 6: 'Write Single Register', 16: 'Write Multiple Registers' },
  },
  {
    id: 'websocket-opcode',
    name: 'WebSocket opcodes',
    values: { 0: 'Continuation', 1: 'Text', 2: 'Binary', 8: 'Close', 9: 'Ping', 10: 'Pong' },
  },
  {
    id: 'pim-type',
    name: 'PIM message types',
    values: { 0: 'Hello', 1: 'Register', 2: 'Register-Stop', 3: 'Join/Prune', 4: 'Bootstrap', 5: 'Assert' },
  },
];
