import type { EnumTable } from '../core/model';

export const enumTables: EnumTable[] = [
  {
    id: 'ethertype',
    name: 'EtherTypes',
    values: {
      0x0800: 'IPv4',
      0x0806: 'ARP',
      0x8100: '802.1Q VLAN',
      0x86dd: 'IPv6',
      0x8847: 'MPLS unicast',
      0x8848: 'MPLS multicast',
      0x8863: 'PPPoE Discovery',
      0x8864: 'PPPoE Session',
      0x88a8: '802.1ad Q-in-Q',
    },
  },
  {
    id: 'ip-proto',
    name: 'IP protocol numbers',
    values: {
      1: 'ICMP',
      2: 'IGMP',
      4: 'IPv4 (encapsulated)',
      6: 'TCP',
      17: 'UDP',
      41: 'IPv6 (encapsulated)',
      47: 'GRE',
      58: 'ICMPv6',
      89: 'OSPF',
      115: 'L2TPv3',
      132: 'SCTP',
    },
  },
  {
    id: 'well-known-port',
    name: 'Well-known ports',
    values: {
      20: 'FTP data',
      21: 'FTP control',
      22: 'SSH',
      23: 'Telnet',
      25: 'SMTP',
      53: 'DNS',
      67: 'DHCP server',
      68: 'DHCP client',
      80: 'HTTP',
      110: 'POP3',
      123: 'NTP',
      143: 'IMAP',
      179: 'BGP',
      443: 'HTTPS',
      1701: 'L2TP',
      4789: 'VXLAN',
    },
  },
  {
    id: 'icmp-type',
    name: 'ICMP types',
    values: {
      0: 'Echo reply',
      3: 'Destination unreachable',
      5: 'Redirect',
      8: 'Echo request',
      11: 'Time exceeded',
      13: 'Timestamp request',
      14: 'Timestamp reply',
    },
  },
  {
    id: 'icmpv6-type',
    name: 'ICMPv6 types',
    values: {
      1: 'Destination unreachable',
      2: 'Packet too big',
      3: 'Time exceeded',
      4: 'Parameter problem',
      128: 'Echo request',
      129: 'Echo reply',
      133: 'Router solicitation',
      134: 'Router advertisement',
      135: 'Neighbor solicitation',
      136: 'Neighbor advertisement',
    },
  },
  {
    id: 'arp-oper',
    name: 'ARP operations',
    values: { 1: 'Request', 2: 'Reply' },
  },
  {
    id: 'dscp',
    name: 'DSCP values',
    values: { 0: 'Default (CS0)', 8: 'CS1', 16: 'CS2', 24: 'CS3', 32: 'CS4', 40: 'CS5', 46: 'EF', 48: 'CS6', 56: 'CS7' },
  },
];
