import type { ProtocolDefinition } from '../core/model';
import { NS } from '../core/bindings';
import { E } from '../core/expr';

export const ipv4: ProtocolDefinition = {
  id: 'ipv4',
  name: 'IPv4',
  fullName: 'Internet Protocol version 4',
  layerHint: 'network',
  source: 'builtin',
  references: ['RFC 791'],
  description:
    'The Internet Protocol. Version, IHL, Total Length, and Header Checksum are computed automatically; the Protocol field is auto-set from the next layer in the stack.',
  fields: [
    {
      id: 'version',
      name: 'Version',
      type: 'uint',
      bitLength: 4,
      default: 4,
      description: 'Always 4 for IPv4.',
    },
    {
      id: 'ihl',
      name: 'IHL',
      type: 'uint',
      bitLength: 4,
      computed: { kind: 'expr', expr: E.div(E.headerBytes(), E.const(4)) },
      description: 'Internet Header Length in 32-bit words (5 with no options).',
    },
    {
      id: 'dscp',
      name: 'DSCP',
      type: 'uint',
      bitLength: 6,
      default: 0,
      enumRef: 'dscp',
      description: 'Differentiated Services Code Point.',
    },
    {
      id: 'ecn',
      name: 'ECN',
      type: 'uint',
      bitLength: 2,
      default: 0,
      description: 'Explicit Congestion Notification.',
    },
    {
      id: 'totalLength',
      name: 'Total Length',
      type: 'uint',
      bitLength: 16,
      computed: { kind: 'expr', expr: E.add(E.headerBytes(), E.payloadBytes()) },
      description: 'Length of header plus payload, in bytes.',
    },
    {
      id: 'identification',
      name: 'Identification',
      type: 'uint',
      bitLength: 16,
      default: 0x0001,
      description: 'Groups fragments of a datagram.',
    },
    {
      id: 'flags',
      name: 'Flags',
      type: 'flags',
      bitLength: 3,
      default: 0b010,
      flags: [
        { bit: 0, name: 'Reserved' },
        { bit: 1, name: 'DF', description: "Don't Fragment" },
        { bit: 2, name: 'MF', description: 'More Fragments' },
      ],
      description: 'Fragmentation control (DF set by default).',
    },
    {
      id: 'fragmentOffset',
      name: 'Fragment Offset',
      type: 'uint',
      bitLength: 13,
      default: 0,
      description: 'Position of this fragment in 8-byte units.',
    },
    {
      id: 'ttl',
      name: 'TTL',
      type: 'uint',
      bitLength: 8,
      default: 64,
      description: 'Time to live: decremented at each hop.',
    },
    {
      id: 'protocol',
      name: 'Protocol',
      type: 'uint',
      bitLength: 8,
      default: 6,
      enumRef: 'ip-proto',
      computed: { kind: 'binding' },
      description: 'Payload protocol number (auto-set from the next layer).',
    },
    {
      id: 'headerChecksum',
      name: 'Header Checksum',
      type: 'uint',
      bitLength: 16,
      computed: { kind: 'checksum', algorithm: 'inet16', scope: 'header' },
      description: 'Internet checksum over the IPv4 header.',
    },
    {
      id: 'src',
      name: 'Source Address',
      type: 'ipv4',
      bitLength: 32,
      default: '192.0.2.1',
      description: 'Sender IPv4 address.',
    },
    {
      id: 'dst',
      name: 'Destination Address',
      type: 'ipv4',
      bitLength: 32,
      default: '198.51.100.1',
      description: 'Receiver IPv4 address.',
    },
    {
      id: 'options',
      name: 'Options',
      type: 'bytes',
      bitLength: 'auto',
      default: new Uint8Array(0),
      description: 'Rarely used; must pad to a multiple of 4 bytes.',
    },
  ],
  providesNamespaces: [
    { id: NS.ipProto, displayName: 'IP Protocol', selectorFieldId: 'protocol' },
  ],
  encapsulations: [
    { namespaceId: NS.ethertype, value: 0x0800 },
    { namespaceId: NS.ipProto, value: 4 }, // IP-in-IP
    { namespaceId: NS.greProto, value: 0x0800 },
    { namespaceId: NS.pppProto, value: 0x0021 },
    { namespaceId: NS.mplsPayload },
    { namespaceId: NS.icmpPayload },
  ],
};
