import type { ProtocolDefinition } from '../core/model';
import { NS } from '../core/bindings';
import { E } from '../core/expr';

export const tcp: ProtocolDefinition = {
  id: 'tcp',
  name: 'TCP',
  fullName: 'Transmission Control Protocol',
  layerHint: 'transport',
  source: 'builtin',
  description:
    'Reliable, connection-oriented transport. Data Offset and Checksum are computed automatically (the checksum includes the IP pseudo-header). The destination port is auto-set when an application protocol follows.',
  fields: [
    {
      id: 'srcPort',
      name: 'Source Port',
      type: 'uint',
      bitLength: 16,
      default: 49152,
      enumRef: 'well-known-port',
      description: 'Sending port (ephemeral by default).',
    },
    {
      id: 'dstPort',
      name: 'Destination Port',
      type: 'uint',
      bitLength: 16,
      default: 80,
      enumRef: 'well-known-port',
      computed: { kind: 'binding' },
      description: 'Receiving port (auto-set from the next layer).',
    },
    {
      id: 'seq',
      name: 'Sequence Number',
      type: 'uint',
      bitLength: 32,
      default: 1000,
      description: 'Position of the first data byte in this segment.',
    },
    {
      id: 'ack',
      name: 'Acknowledgment Number',
      type: 'uint',
      bitLength: 32,
      default: 0,
      description: 'Next byte expected from the peer (valid when ACK set).',
    },
    {
      id: 'dataOffset',
      name: 'Data Offset',
      type: 'uint',
      bitLength: 4,
      computed: { kind: 'expr', expr: E.div(E.headerBytes(), E.const(4)) },
      description: 'Header length in 32-bit words (5 with no options).',
    },
    {
      id: 'reserved',
      name: 'Reserved',
      type: 'uint',
      bitLength: 4,
      default: 0,
      description: 'Must be zero.',
    },
    {
      id: 'flags',
      name: 'Flags',
      type: 'flags',
      bitLength: 8,
      default: 0x02,
      flags: [
        { bit: 0, name: 'CWR', description: 'Congestion Window Reduced' },
        { bit: 1, name: 'ECE', description: 'ECN Echo' },
        { bit: 2, name: 'URG', description: 'Urgent pointer valid' },
        { bit: 3, name: 'ACK', description: 'Acknowledgment valid' },
        { bit: 4, name: 'PSH', description: 'Push buffered data' },
        { bit: 5, name: 'RST', description: 'Reset connection' },
        { bit: 6, name: 'SYN', description: 'Synchronize sequence numbers' },
        { bit: 7, name: 'FIN', description: 'No more data from sender' },
      ],
      description: 'Control flags (SYN set by default).',
    },
    {
      id: 'window',
      name: 'Window',
      type: 'uint',
      bitLength: 16,
      default: 65535,
      description: 'Receive window size in bytes.',
    },
    {
      id: 'checksum',
      name: 'Checksum',
      type: 'uint',
      bitLength: 16,
      computed: {
        kind: 'checksum',
        algorithm: 'inet16',
        scope: 'headerAndPayload',
        pseudoHeader: 'auto',
      },
      description: 'Internet checksum over pseudo-header, header, and payload.',
    },
    {
      id: 'urgentPointer',
      name: 'Urgent Pointer',
      type: 'uint',
      bitLength: 16,
      default: 0,
      description: 'Offset of urgent data (valid when URG set).',
    },
    {
      id: 'options',
      name: 'Options',
      type: 'bytes',
      bitLength: 'auto',
      decodeBitLength: { expr: E.mul(E.sub(E.field('dataOffset'), E.const(5)), E.const(4)), unit: 'bytes' },
      default: new Uint8Array(0),
      description: 'TCP options. Common SYN options have a structured editor and are padded automatically to a 32-bit boundary; unknown options remain editable as raw hex.',
    },
  ],
  providesNamespaces: [
    { id: NS.tcpDstPort, displayName: 'TCP port', selectorFieldId: 'dstPort' },
  ],
  encapsulations: [{ namespaceId: NS.ipProto, value: 6 }],
};
