import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import { ArrowRight, Check, Dices, Search, X } from 'lucide-react';
import {
  accuracy,
  EMPTY_SCORE,
  generateRound,
  scoreAnswer,
  type QuizQuestion,
  type QuizRound,
  type QuizSource,
  type Score,
} from '../../core/quiz';
import { useLibraryStore } from '../../store/libraryStore';
import { useStackStore } from '../../store/stackStore';
import { useHighlightStore } from '../../store/highlightStore';
import { usePrefersReducedMotion } from '../usePrefersReducedMotion';
import PlainHexView from '../components/PlainHexView';
import ProtocolInfoLink from '../components/ProtocolInfoLink';
import { referencesFor } from '../../protocols/refs';

const SOURCES: { id: QuizSource; label: string; description: string }[] = [
  {
    id: 'random',
    label: 'Random stacks',
    description: 'Generated by walking the encapsulation graph — anything the library can build.',
  },
  {
    id: 'curated',
    label: 'Common packets',
    description: 'Drawn from the builder presets: the stacks worth knowing cold.',
  },
];

/** Number keys pick an answer, so a whole session is one-handed. */
const CHOICE_KEYS = ['1', '2', '3', '4', '5', '6'];

const QUESTIONS_PER_ROUND = 5;

/**
 * "Identify the packet" — active recall over a real generated packet.
 *
 * The page deliberately shows *less* than every other view in the app: an
 * unannotated hex dump and nothing else. The stack strip, the layer tinting,
 * the field editor and the diagrams all answer the questions being asked, so
 * none of them appear until the learner has committed to an answer. Once they
 * have, the reveal is generous — the explanation, the specification citation,
 * and a link that loads the packet into the Stack Builder, where every one of
 * those views is available for a proper look.
 */
export default function PracticePage() {
  const registry = useLibraryStore((state) => state.registry);
  const restoreStack = useStackStore((state) => state.restoreStack);
  const toggleLocked = useHighlightStore((state) => state.toggleLocked);
  const navigate = useNavigate();
  const reducedMotion = usePrefersReducedMotion();

  const [source, setSource] = useState<QuizSource>('random');
  const [round, setRound] = useState<QuizRound | null>(() =>
    generateRound(registry, 'random', { count: QUESTIONS_PER_ROUND }),
  );
  const [index, setIndex] = useState(0);
  const [answered, setAnswered] = useState<string | null>(null);
  const [score, setScore] = useState<Score>(EMPTY_SCORE);

  const nextRound = useCallback(
    (from: QuizSource) => {
      setRound(generateRound(registry, from, { count: QUESTIONS_PER_ROUND }));
      setIndex(0);
      setAnswered(null);
    },
    [registry],
  );

  // Draw a fresh packet when the source changes, or when custom protocols
  // finish loading and widen the library. Done during render rather than in
  // an effect, which would show one round then immediately replace it.
  const [drawnFor, setDrawnFor] = useState({ source, registry });
  if (drawnFor.source !== source || drawnFor.registry !== registry) {
    setDrawnFor({ source, registry });
    nextRound(source);
  }

  const question: QuizQuestion | null = round?.questions[index] ?? null;
  // The reveal cites the protocol's own specification, resolved the same way
  // the library does so a quiz link and a library link never disagree.
  const reference = question
    ? referencesFor(question.protocolId, registry.get(question.protocolId)?.references ?? [])[0]
    : undefined;
  const chosen = question?.choices.find((choice) => choice.id === answered) ?? null;
  const correct = question?.choices.find((choice) => choice.correct) ?? null;
  const wasCorrect = chosen?.correct === true;

  const answer = useCallback(
    (choiceId: string) => {
      if (!question || answered !== null) return;
      setAnswered(choiceId);
      setScore((current) =>
        scoreAnswer(current, question.choices.find((c) => c.id === choiceId)?.correct === true),
      );
    },
    [question, answered],
  );

  const advance = useCallback(() => {
    if (!round) return;
    if (index + 1 < round.questions.length) {
      setIndex(index + 1);
      setAnswered(null);
    } else {
      nextRound(source);
    }
  }, [round, index, nextRound, source]);

  /** Load this packet into the builder and point the inspector at the field. */
  const inspect = () => {
    if (!round || !question) return;
    restoreStack(round.stack.layers, round.stack.trailingPayload);
    // Layer uids are reassigned by `restoreStack`, so the highlight is set by
    // position: the nth layer of the restored stack is the nth of this one.
    const layerIndex = round.stack.layers.findIndex((l) => l.uid === question.focus.layerUid);
    const fieldId = question.focus.fieldId;
    if (layerIndex >= 0 && fieldId !== undefined) {
      const restored = useStackStore.getState().layers[layerIndex];
      if (restored) toggleLocked({ layerUid: restored.uid, fieldId });
    }
    navigate('/builder');
  };

  // Shortcuts are bound at the window rather than to a container, so they
  // work wherever focus happens to be — a learner reading the hex dump should
  // not have to tab back to the questions to answer one.
  useEffect(() => {
    if (!question) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      const tag = (e.target as HTMLElement | null)?.tagName ?? '';
      if (tag === 'INPUT' || tag === 'SELECT' || tag === 'TEXTAREA') return;

      const slot = CHOICE_KEYS.indexOf(e.key);
      if (slot >= 0 && answered === null) {
        const choice = question.choices[slot];
        if (choice) {
          e.preventDefault();
          answer(choice.id);
        }
        return;
      }
      // A focused button handles its own Enter; intercepting it here as well
      // would advance twice.
      if (e.key === 'Enter' && answered !== null && tag !== 'BUTTON' && tag !== 'A') {
        e.preventDefault();
        advance();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [question, answered, answer, advance]);

  const transition = reducedMotion ? '' : 'transition-colors';
  const total = round?.questions.length ?? 0;

  return (
    <div className="flex h-full flex-col">
      <header className="flex flex-wrap items-center gap-3 border-b border-zinc-800 px-6 py-3">
        <h1 className="text-[15px] font-semibold tracking-tight text-zinc-100">Packet Practice</h1>
        <label className="flex items-center gap-2 text-[12px] text-zinc-400">
          <span className="sr-only">Packet source</span>
          <select
            className="cursor-pointer rounded-md border border-zinc-700 bg-zinc-900 px-2 py-1 text-[12px] text-zinc-200 outline-none focus:border-cyan-600"
            value={source}
            onChange={(e) => setSource(e.target.value as QuizSource)}
          >
            {SOURCES.map((option) => (
              <option key={option.id} value={option.id}>
                {option.label}
              </option>
            ))}
          </select>
        </label>
        <button
          className="flex cursor-pointer items-center gap-1.5 rounded-md border border-zinc-700 px-2.5 py-1 text-[12px] text-zinc-300 hover:border-cyan-600 hover:text-cyan-300"
          onClick={() => nextRound(source)}
        >
          <Dices className="size-3.5" aria-hidden />
          New packet
        </button>
        <ScoreBoard score={score} />
      </header>

      <p className="border-b border-zinc-800 bg-zinc-900/30 px-6 py-2 text-[12px] text-zinc-500">
        {SOURCES.find((option) => option.id === source)?.description} Questions are generated from
        the protocol definitions themselves, so custom protocols you import are included
        automatically.
      </p>

      {!round || !question ? (
        <div className="flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center">
          <p className="text-sm text-zinc-400">No questions could be generated.</p>
          <p className="max-w-md text-[13px] text-zinc-600">
            This needs a library with a few protocols that share a layer, so questions have
            plausible wrong answers to offer. Try the other packet source.
          </p>
        </div>
      ) : (
        <div className="grid min-h-0 flex-1 gap-6 overflow-auto px-6 py-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,28rem)]">
          <section aria-labelledby="question-prompt" className="flex min-w-0 flex-col gap-4">
            <p className="font-mono text-[11px] text-zinc-600">
              Question {index + 1} of {total}
            </p>
            <h2 id="question-prompt" className="text-[15px] leading-relaxed text-zinc-100">
              {question.prompt}
            </h2>

            <ul className="flex flex-col gap-2">
              {question.choices.map((choice, i) => {
                const isChosen = choice.id === answered;
                const revealed = answered !== null;
                const state = !revealed
                  ? 'border-zinc-800 hover:border-cyan-700 hover:bg-cyan-500/5'
                  : choice.correct
                    ? 'border-emerald-600 bg-emerald-500/10'
                    : isChosen
                      ? 'border-rose-600 bg-rose-500/10'
                      : 'border-zinc-800 opacity-60';
                return (
                  <li key={choice.id}>
                    <button
                      className={`flex w-full cursor-pointer items-center gap-3 rounded-lg border px-3 py-2.5 text-left text-[13px] text-zinc-200 disabled:cursor-default ${transition} ${state}`}
                      disabled={revealed}
                      onClick={() => answer(choice.id)}
                    >
                      <span className="flex size-5 shrink-0 items-center justify-center rounded border border-zinc-700 font-mono text-[11px] text-zinc-500">
                        {CHOICE_KEYS[i] ?? '·'}
                      </span>
                      <span className="min-w-0 flex-1">{choice.label}</span>
                      {revealed && choice.correct && (
                        <span className="flex shrink-0 items-center gap-1 text-[11px] font-medium text-emerald-300">
                          <Check className="size-3.5" aria-hidden />
                          Correct answer
                        </span>
                      )}
                      {revealed && isChosen && !choice.correct && (
                        <span className="flex shrink-0 items-center gap-1 text-[11px] font-medium text-rose-300">
                          <X className="size-3.5" aria-hidden />
                          Your answer
                        </span>
                      )}
                    </button>
                  </li>
                );
              })}
            </ul>

            <div role="status" aria-live="polite" className="min-h-24">
              {answered !== null && (
                <div className="flex flex-col gap-2 rounded-lg border border-zinc-800 bg-zinc-900/50 p-4">
                  <p
                    className={`text-[13px] font-medium ${wasCorrect ? 'text-emerald-300' : 'text-rose-300'}`}
                  >
                    {wasCorrect ? 'Correct.' : `Not quite — the answer is ${correct?.label}.`}
                  </p>
                  <p className="text-[13px] leading-relaxed text-zinc-300">
                    {question.explanation}
                  </p>
                  <p className="text-[12px] text-zinc-500">{round.sourceLabel}</p>
                  <div className="mt-1 flex flex-wrap items-center gap-2">
                    <button
                      className="flex cursor-pointer items-center gap-1.5 rounded-md bg-cyan-700 px-3 py-1.5 text-[13px] font-medium text-white hover:bg-cyan-600"
                      onClick={advance}
                    >
                      {index + 1 < total ? 'Next question' : 'Next packet'}
                      <ArrowRight className="size-3.5" aria-hidden />
                    </button>
                    <button
                      className="flex cursor-pointer items-center gap-1.5 rounded-md border border-zinc-700 px-3 py-1.5 text-[13px] text-zinc-300 hover:border-cyan-600 hover:text-cyan-300"
                      onClick={inspect}
                    >
                      <Search className="size-3.5" aria-hidden />
                      Inspect in Stack Builder
                    </button>
                    <span className="flex items-center gap-2 text-[12px] text-zinc-500">
                      {reference &&
                        (reference.url ? (
                          <a
                            className="hover:text-cyan-300 hover:underline"
                            href={reference.url}
                            target="_blank"
                            rel="noreferrer noopener"
                            title={`${reference.name} (opens in a new tab)`}
                          >
                            {reference.name}
                          </a>
                        ) : (
                          reference.name
                        ))}
                      <ProtocolInfoLink
                        protocolId={question.protocolId}
                        name={question.protocolName}
                      />
                    </span>
                  </div>
                </div>
              )}
            </div>
          </section>

          <section
            aria-label="Packet bytes"
            className="min-w-0 rounded-lg border border-zinc-800 bg-zinc-950/40 p-3"
          >
            <p className="mb-2 text-[11px] tracking-widest text-zinc-500 uppercase">
              Packet bytes · {round.packet.bytes.length} bytes
            </p>
            <PlainHexView
              bytes={round.packet.bytes}
              ranges={[question.range]}
              muted={answered !== null}
            />
          </section>
        </div>
      )}
    </div>
  );
}

/**
 * The running session score. Each figure carries a spelled-out label, since
 * "1/3" read aloud is not the same information as "1 of 3 correct" — and it
 * gives tests something stable to assert on.
 */
function ScoreBoard({ score }: { score: Score }) {
  return (
    <dl className="ml-auto flex items-center gap-4 text-[12px]">
      <div className="flex items-center gap-1.5">
        <dt className="text-zinc-500">Score</dt>
        <dd
          className="font-mono text-zinc-200"
          aria-label={`${score.correct} of ${score.asked} correct`}
        >
          {score.correct}/{score.asked}
        </dd>
      </div>
      <div className="flex items-center gap-1.5">
        <dt className="text-zinc-500">Accuracy</dt>
        <dd className="font-mono text-zinc-200" aria-label={`${accuracy(score)} percent accuracy`}>
          {accuracy(score)}%
        </dd>
      </div>
      <div className="flex items-center gap-1.5">
        <dt className="text-zinc-500">Streak</dt>
        <dd
          className="font-mono text-zinc-200"
          aria-label={`Current streak ${score.streak}, best ${score.bestStreak}`}
        >
          {score.streak}
          {score.bestStreak > 0 && (
            <span className="text-zinc-500"> (best {score.bestStreak})</span>
          )}
        </dd>
      </div>
    </dl>
  );
}
